spring:
  datasource:
    url: jdbc:mysql://localhost:3306/stackoverflow?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: ********
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
    show-sql: true


repository-type: DATA





